# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20171220_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='from_person',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_person',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='exam.User'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
